export const GET_NOW_PLAYING_MOVIE = 'GET_NOW_PLAYING_MOVIE';
export const GET_POPULAR_MOVIE = 'GET_POPULAR_MOVIE';
export const GET_TOP_RATED_MOVIE = 'GET_TOP_RATED_MOVIE';
export const GET_UPCOMING_MOVIE = 'GET_UPCOMING_MOVIE';
export const SET_ERROR = 'SET_ERROR';
